/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef userintent_CONSTANTS_H
#define userintent_CONSTANTS_H

#include "userintent_types.h"

namespace intentionreg {

class userintentConstants {
 public:
  userintentConstants();

};

extern const userintentConstants g_userintent_constants;

} // namespace

#endif
