/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "userintent_constants.h"

namespace intentionreg {

const userintentConstants g_userintent_constants;

userintentConstants::userintentConstants() {
}

} // namespace

